"""Science-backed enrichment data for existing exercise library entries.

This module provides the enrichment fields (EMG rank, rep ranges, rest times,
tempo, starting weight multipliers, posture corrections, progressions) that
are merged into SEED_EXERCISES at import time. Data sourced from:
- Schoenfeld (2016, 2019), Paoli et al. (2017)
- Stronger by Science meta-analysis (2024)
- Compendium of Physical Activities (Ainsworth et al.)
- ACE Fitness, NSCA guidelines
"""

# Maps exercise name -> enrichment dict.  Merged into SEED_EXERCISES by exercise_service.py
ENRICHMENT = {
    # ── BACK ─────────────────────────────────────────────────────────────────
    "Barbell Row": {
        "emg_rank": 2,
        "muscle_primary": ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
        "muscle_secondary": ["Rear Deltoid", "Biceps Brachii", "Erector Spinae"],
        "reps_min": 6, "reps_max": 10,
        "rest_seconds": 180,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.35, "starting_weight_mult_female": 0.25,
        "posture_correction_tags": ["rounded_shoulders", "forward_head_posture"],
        "progressions": ["Pendlay Row", "Chest-Supported Row", "Yates Row"],
    },
    "Pull-up": {
        "emg_rank": 1,
        "muscle_primary": ["Latissimus Dorsi", "Teres Major"],
        "muscle_secondary": ["Biceps Brachii", "Rear Deltoid", "Rhomboids", "Core"],
        "reps_min": 5, "reps_max": 10,
        "rest_seconds": 180,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "posture_correction_tags": ["forward_head_posture", "rounded_shoulders"],
        "progressions": ["Weighted Pull-Up", "Typewriter Pull-Up"],
        "regressions": ["Band-Assisted Pull-Up", "Lat Pulldown", "Inverted Row"],
    },
    "Lat Pulldown": {
        "emg_rank": 3,
        "muscle_primary": ["Latissimus Dorsi"],
        "muscle_secondary": ["Biceps Brachii", "Rear Deltoid"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 120,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.40, "starting_weight_mult_female": 0.30,
        "progressions": ["Pull-up", "Weighted Pull-Up"],
    },
    "Dumbbell Row": {
        "emg_rank": 3,
        "muscle_primary": ["Latissimus Dorsi", "Rhomboids"],
        "muscle_secondary": ["Rear Deltoid", "Biceps Brachii", "Core"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 120,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.20, "starting_weight_mult_female": 0.13,
        "progressions": ["Chest-Supported Row", "Meadows Row", "Barbell Row"],
    },
    "Deadlift": {
        "emg_rank": 1,
        "muscle_primary": ["Erector Spinae", "Latissimus Dorsi", "Glutes", "Hamstrings"],
        "muscle_secondary": ["Trapezius", "Rhomboids", "Forearms", "Quadriceps"],
        "reps_min": 4, "reps_max": 6,
        "rest_seconds": 300,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.70, "starting_weight_mult_female": 0.50,
        "posture_correction_tags": ["anterior_pelvic_tilt", "rounded_shoulders"],
        "progressions": ["Romanian Deadlift", "Trap Bar Deadlift", "Sumo Deadlift"],
    },
    "Face Pull": {
        "emg_rank": 1,
        "muscle_primary": ["Rear Deltoid", "Infraspinatus", "Teres Minor"],
        "muscle_secondary": ["Middle Trapezius", "Rhomboids", "External Rotators"],
        "reps_min": 15, "reps_max": 20,
        "rest_seconds": 60,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
        "posture_correction_tags": ["rounded_shoulders", "forward_head_posture"],
    },
    "Seated Cable Row": {
        "emg_rank": 4,
        "muscle_primary": ["Latissimus Dorsi", "Rhomboids"],
        "muscle_secondary": ["Biceps Brachii", "Rear Deltoid"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 120,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.35, "starting_weight_mult_female": 0.25,
    },
    "Straight-Arm Pulldown": {
        "emg_rank": 5,
        "muscle_primary": ["Latissimus Dorsi"],
        "muscle_secondary": ["Teres Major", "Posterior Deltoid"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    # ── SHOULDERS ────────────────────────────────────────────────────────────
    "Overhead Press": {
        "emg_rank": 1,
        "muscle_primary": ["Anterior Deltoid", "Medial Deltoid", "Triceps Brachii"],
        "muscle_secondary": ["Upper Trapezius", "Serratus Anterior", "Core"],
        "reps_min": 5, "reps_max": 8,
        "rest_seconds": 180,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.25, "starting_weight_mult_female": 0.18,
        "progressions": ["Push Press", "Seated DB Press", "Arnold Press"],
    },
    "Dumbbell Shoulder Press": {
        "emg_rank": 2,
        "muscle_primary": ["Anterior Deltoid", "Medial Deltoid"],
        "muscle_secondary": ["Triceps Brachii", "Upper Trapezius"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 150,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    "Lateral Raise": {
        "emg_rank": 1,
        "muscle_primary": ["Medial Deltoid"],
        "muscle_secondary": ["Anterior Deltoid", "Upper Trapezius"],
        "reps_min": 12, "reps_max": 20,
        "rest_seconds": 60,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.05, "starting_weight_mult_female": 0.035,
    },
    "Rear Delt Fly": {
        "emg_rank": 2,
        "muscle_primary": ["Rear Deltoid"],
        "muscle_secondary": ["Middle Trapezius", "Rhomboids"],
        "reps_min": 12, "reps_max": 20,
        "rest_seconds": 60,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.05, "starting_weight_mult_female": 0.035,
        "posture_correction_tags": ["rounded_shoulders"],
    },
    "Arnold Press": {
        "emg_rank": 3,
        "muscle_primary": ["Anterior Deltoid", "Medial Deltoid"],
        "muscle_secondary": ["Triceps Brachii"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 120,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.12, "starting_weight_mult_female": 0.08,
    },
    # ── ARMS ─────────────────────────────────────────────────────────────────
    "Dumbbell Curl": {
        "emg_rank": 2,
        "muscle_primary": ["Biceps Brachii (long & short head)"],
        "muscle_secondary": ["Brachialis", "Brachioradialis"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.10, "starting_weight_mult_female": 0.07,
    },
    "Incline Dumbbell Curl": {
        "emg_rank": 2,
        "muscle_primary": ["Biceps Brachii (long head)"],
        "muscle_secondary": ["Brachialis"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.08, "starting_weight_mult_female": 0.05,
    },
    "Hammer Curl": {
        "emg_rank": 3,
        "muscle_primary": ["Brachialis", "Brachioradialis"],
        "muscle_secondary": ["Biceps Brachii"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.10, "starting_weight_mult_female": 0.07,
    },
    "EZ Bar Curl": {
        "emg_rank": 1,
        "muscle_primary": ["Biceps Brachii (long & short head)"],
        "muscle_secondary": ["Brachialis", "Brachioradialis"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    "Tricep Pushdown": {
        "emg_rank": 3,
        "muscle_primary": ["Triceps Brachii (lateral & medial head)"],
        "muscle_secondary": [],
        "reps_min": 12, "reps_max": 20,
        "rest_seconds": 60,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    "Overhead Tricep Extension": {
        "emg_rank": 2,
        "muscle_primary": ["Triceps Brachii (long head)"],
        "muscle_secondary": ["Lateral and Medial Tricep Heads"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.12, "starting_weight_mult_female": 0.08,
    },
    "Skull Crusher": {
        "emg_rank": 1,
        "muscle_primary": ["Triceps Brachii (all heads)"],
        "muscle_secondary": [],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    # ── LEGS ─────────────────────────────────────────────────────────────────
    "Squat": {
        "emg_rank": 1,
        "muscle_primary": ["Quadriceps", "Glutes", "Adductors"],
        "muscle_secondary": ["Hamstrings", "Erector Spinae", "Core", "Calves"],
        "reps_min": 5, "reps_max": 8,
        "rest_seconds": 300,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.50, "starting_weight_mult_female": 0.35,
        "posture_correction_tags": ["anterior_pelvic_tilt"],
        "progressions": ["Front Squat", "Pause Squat", "Box Squat"],
        "regressions": ["Goblet Squat", "Leg Press", "Bulgarian Split Squat"],
    },
    "Romanian Deadlift": {
        "emg_rank": 1,
        "muscle_primary": ["Hamstrings", "Glutes"],
        "muscle_secondary": ["Erector Spinae", "Adductors"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 180,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.50, "starting_weight_mult_female": 0.35,
        "posture_correction_tags": ["anterior_pelvic_tilt"],
    },
    "Leg Press": {
        "emg_rank": 3,
        "muscle_primary": ["Quadriceps", "Glutes"],
        "muscle_secondary": ["Hamstrings", "Adductors"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 150,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 1.0, "starting_weight_mult_female": 0.70,
    },
    "Bulgarian Split Squat": {
        "emg_rank": 2,
        "muscle_primary": ["Quadriceps", "Glutes"],
        "muscle_secondary": ["Hamstrings", "Adductors", "Core"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 120,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    "Hip Thrust": {
        "emg_rank": 1,
        "muscle_primary": ["Gluteus Maximus"],
        "muscle_secondary": ["Hamstrings", "Adductors", "Core"],
        "reps_min": 8, "reps_max": 15,
        "rest_seconds": 120,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.40, "starting_weight_mult_female": 0.25,
        "posture_correction_tags": ["anterior_pelvic_tilt"],
    },
    "Leg Curl": {
        "emg_rank": 2,
        "muscle_primary": ["Hamstrings"],
        "muscle_secondary": [],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.25, "starting_weight_mult_female": 0.18,
    },
    "Leg Extension": {
        "emg_rank": 3,
        "muscle_primary": ["Quadriceps"],
        "muscle_secondary": [],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.30, "starting_weight_mult_female": 0.20,
    },
    "Calf Raise": {
        "emg_rank": 1,
        "muscle_primary": ["Gastrocnemius"],
        "muscle_secondary": ["Soleus"],
        "reps_min": 12, "reps_max": 20,
        "rest_seconds": 60,
        "tempo_eccentric": 3, "tempo_concentric": 1,
    },
    "Walking Lunge": {
        "emg_rank": 4,
        "muscle_primary": ["Quadriceps", "Glutes"],
        "muscle_secondary": ["Hamstrings", "Core"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 120,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
    },
    "Front Squat": {
        "emg_rank": 2,
        "muscle_primary": ["Quadriceps", "Glutes", "Core"],
        "muscle_secondary": ["Hamstrings", "Upper Back"],
        "reps_min": 5, "reps_max": 8,
        "rest_seconds": 240,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.40, "starting_weight_mult_female": 0.28,
        "progressions": ["Pause Squat"],
        "regressions": ["Goblet Squat"],
    },
    # ── CORE ─────────────────────────────────────────────────────────────────
    "Plank": {
        "emg_rank": 3,
        "muscle_primary": ["Rectus Abdominis", "Transverse Abdominis"],
        "muscle_secondary": ["Obliques", "Shoulders"],
        "reps_min": 30, "reps_max": 60,  # seconds
        "rest_seconds": 60,
    },
    "Ab Wheel Rollout": {
        "emg_rank": 1,
        "muscle_primary": ["Rectus Abdominis", "Transverse Abdominis"],
        "muscle_secondary": ["Hip Flexors", "Lats", "Shoulders"],
        "reps_min": 6, "reps_max": 10,
        "rest_seconds": 90,
        "progressions": ["Standing Ab Wheel Rollout"],
        "regressions": ["Plank", "Dead Bug"],
    },
    "Hanging Leg Raise": {
        "emg_rank": 2,
        "muscle_primary": ["Rectus Abdominis (lower)", "Hip Flexors"],
        "muscle_secondary": ["Obliques", "Grip/Forearms"],
        "reps_min": 8, "reps_max": 15,
        "rest_seconds": 90,
        "regressions": ["Knee Raise", "Captain's Chair Leg Raise"],
    },
    "Russian Twist": {
        "emg_rank": 4,
        "muscle_primary": ["Obliques"],
        "muscle_secondary": ["Rectus Abdominis", "Hip Flexors"],
        "reps_min": 15, "reps_max": 25,
        "rest_seconds": 60,
    },
    "Dead Bug": {
        "emg_rank": 2,
        "muscle_primary": ["Transverse Abdominis", "Rectus Abdominis"],
        "muscle_secondary": ["Hip Flexors", "Multifidus"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 60,
        "posture_correction_tags": ["anterior_pelvic_tilt"],
    },
    "Glute Bridge": {
        "emg_rank": 1,
        "muscle_primary": ["Gluteus Maximus"],
        "muscle_secondary": ["Hamstrings", "Core"],
        "reps_min": 15, "reps_max": 20,
        "rest_seconds": 60,
        "posture_correction_tags": ["anterior_pelvic_tilt"],
        "progressions": ["Single-Leg Glute Bridge", "Barbell Hip Thrust"],
    },
    # ── CARDIO ───────────────────────────────────────────────────────────────
    "Jump Rope": {
        "muscle_primary": ["Calves", "Core"],
        "muscle_secondary": ["Shoulders", "Forearms"],
        "reps_min": 30, "reps_max": 120,  # seconds
        "rest_seconds": 30,
    },
    "Burpee": {
        "muscle_primary": ["Full Body"],
        "muscle_secondary": ["Core", "Chest", "Quadriceps"],
        "reps_min": 8, "reps_max": 15,
        "rest_seconds": 60,
    },
    "Mountain Climber": {
        "muscle_primary": ["Core", "Hip Flexors"],
        "muscle_secondary": ["Shoulders", "Quadriceps"],
        "reps_min": 20, "reps_max": 40,
        "rest_seconds": 45,
    },
    # ── STRETCHES / MOBILITY ─────────────────────────────────────────────────
    "Hip Flexor Stretch": {
        "muscle_primary": ["Hip Flexors", "Quadriceps"],
        "muscle_secondary": ["Psoas"],
        "posture_correction_tags": ["anterior_pelvic_tilt"],
    },
    "Doorway Chest Stretch": {
        "muscle_primary": ["Pectoralis Major", "Anterior Deltoid"],
        "muscle_secondary": ["Biceps"],
        "posture_correction_tags": ["rounded_shoulders"],
    },
    "Chin Tuck": {
        "muscle_primary": ["Deep Cervical Flexors"],
        "muscle_secondary": ["Upper Back"],
        "posture_correction_tags": ["forward_head_posture"],
    },
    "Band Pull-Apart": {
        "emg_rank": 1,
        "muscle_primary": ["Rear Deltoid", "Rhomboids", "Middle Trapezius"],
        "muscle_secondary": ["External Rotators"],
        "reps_min": 15, "reps_max": 25,
        "rest_seconds": 45,
        "posture_correction_tags": ["rounded_shoulders"],
    },
}
