"""Exercise library seed data — 60+ exercises with MET values, calorie data, split tags,
and science-backed enrichment (EMG rank, rep ranges, rest/tempo, starting weights, posture links).
"""

from sqlalchemy.orm import Session
from backend.models.database import ExerciseLibrary
from backend.services.exercise_enrichment import ENRICHMENT


# MET values are per-exercise at moderate intensity.
# Calorie burn = MET × weight_kg × duration_hours
# calories_per_min is pre-calculated at 75kg reference body weight.

SEED_EXERCISES = [
    # ─── CHEST ───────────────────────────────────────────────────────────────
    {
        "name": "Bench Press",
        "description": "Compound chest exercise using a barbell on a flat bench.",
        "instructions_json": [
            "Lie flat on bench, eyes under the bar",
            "Grip slightly wider than shoulder-width (index fingers on knurling ring)",
            "Retract and depress scapulae — create an arch in upper back",
            "Unrack bar, hold directly over lower chest",
            "Lower bar with control to lower chest (nipple line), touch lightly",
            "Drive bar back up in a slight arc, pressing through your chest not shoulders",
            "Lock out at top without shrugging",
        ],
        "muscle_groups": ["chest", "shoulders", "triceps"],
        "common_mistakes": [
            "Bar touching too high (upper chest/throat) — damages shoulders",
            "Flaring elbows to 90° — keep at 45-75°",
            "Bouncing bar off chest — controlled touch only",
            "Feet off the floor — reduces stability and power transfer",
            "Not retracting scapulae — kills chest activation",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif",
        "difficulty": "beginner",
        "equipment_needed": ["barbell", "bench", "rack"],
        "calories_per_min": 6.5,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder", "upper_body"],
        "emg_rank": 1,
        "muscle_primary": ["Pectoralis Major (sternal & clavicular)"],
        "muscle_secondary": ["Anterior Deltoid", "Triceps Brachii"],
        "reps_min": 6, "reps_max": 10,
        "rest_seconds": 180,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.35, "starting_weight_mult_female": 0.25,
        "progressions": ["Paused Bench Press", "Close-Grip Bench", "Weighted Dips"],
        "regressions": ["Push-up", "Machine Chest Press"],
    },
    {
        "name": "Incline Dumbbell Press",
        "description": "Upper chest focused pressing movement at 30° incline.",
        "instructions_json": [
            "Set bench to exactly 30° — beyond 45° shifts load to front delts",
            "Hold dumbbells at shoulder height, palms facing forward",
            "Press dumbbells up and slightly together at the top",
            "Lower with full control, get a deep stretch at the bottom",
            "Keep wrists directly over elbows throughout",
        ],
        "muscle_groups": ["upper chest", "shoulders", "triceps"],
        "common_mistakes": [
            "Bench too steep (>45°) shifts all load to shoulders",
            "Short range of motion — always get full stretch at bottom",
            "Dumbbells not touching at top — miss peak contraction",
            "Not retracting shoulder blades",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells", "adjustable bench"],
        "calories_per_min": 6.0,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder", "upper_body"],
        "emg_rank": 2,
        "muscle_primary": ["Pectoralis Major (upper/clavicular head)"],
        "muscle_secondary": ["Anterior Deltoid", "Triceps Brachii"],
        "reps_min": 8, "reps_max": 12,
        "rest_seconds": 150,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.15, "starting_weight_mult_female": 0.10,
        "progressions": ["Incline Barbell Press", "Cable Fly"],
    },
    {
        "name": "Cable Fly",
        "description": "Chest isolation exercise using cables from low pulley.",
        "instructions_json": [
            "Set pulleys to lowest position",
            "Stand between cables, step forward, slight forward lean",
            "Arms slightly bent throughout — never lock elbows",
            "Draw hands up and together in arc motion toward shoulder height",
            "Squeeze chest hard at top, then lower with full control",
        ],
        "muscle_groups": ["chest"],
        "common_mistakes": [
            "Bending elbows like a press — this becomes a chest press, not a fly",
            "Leaning too far forward — reduces range of motion",
            "Going too heavy — ruins arc and turns into a press",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Cable-Crossover.gif",
        "difficulty": "beginner",
        "equipment_needed": ["cable machine"],
        "calories_per_min": 4.5,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
        "emg_rank": 3,
        "muscle_primary": ["Pectoralis Major (upper)"],
        "muscle_secondary": ["Anterior Deltoid"],
        "reps_min": 12, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.12, "starting_weight_mult_female": 0.08,
        "progressions": ["Weighted Dips", "Pec Deck"],
    },
    {
        "name": "Push-up",
        "description": "Classic bodyweight chest and tricep movement.",
        "instructions_json": [
            "Start in a high plank, hands slightly wider than shoulder width",
            "Keep body perfectly straight from head to heels",
            "Lower chest to just above the floor",
            "Push back up to full arm extension",
            "Squeeze chest at the top",
        ],
        "muscle_groups": ["chest", "triceps", "shoulders", "core"],
        "common_mistakes": [
            "Hips sagging or piking up",
            "Partial range of motion",
            "Flaring elbows 90 degrees (use 45-75 degrees)",
            "Head drooping forward",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Push-Up.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 5.5,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder", "upper_body", "bodyweight"],
        "emg_rank": 4,
        "muscle_primary": ["Pectoralis Major"],
        "muscle_secondary": ["Anterior Deltoid", "Triceps Brachii", "Core"],
        "reps_min": 10, "reps_max": 25,
        "rest_seconds": 90,
        "tempo_eccentric": 2, "tempo_concentric": 1,
        "progressions": ["Weighted Push-up", "Bench Press"],
    },
    {
        "name": "Dumbbell Chest Fly",
        "description": "Dumbbell isolation fly for chest stretch and squeeze.",
        "instructions_json": [
            "Lie on a flat bench holding dumbbells above chest",
            "Slight bend in elbows throughout — never straighten",
            "Lower dumbbells out in a wide arc until you feel a stretch",
            "Squeeze chest to bring dumbbells back up",
            "Don't let dumbbells touch at the top",
        ],
        "muscle_groups": ["chest"],
        "common_mistakes": [
            "Keeping arms too straight (joint stress)",
            "Dropping weights too fast",
            "Not feeling the stretch at the bottom",
            "Using too much weight",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells", "bench"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
        "emg_rank": 5,
        "muscle_primary": ["Pectoralis Major"],
        "muscle_secondary": ["Anterior Deltoid"],
        "reps_min": 10, "reps_max": 15,
        "rest_seconds": 90,
        "tempo_eccentric": 3, "tempo_concentric": 1,
        "starting_weight_mult_male": 0.10, "starting_weight_mult_female": 0.07,
    },
    # ─── BACK ────────────────────────────────────────────────────────────────
    {
        "name": "Barbell Row",
        "description": "Bent-over rowing movement for back thickness.",
        "instructions_json": [
            "Hinge forward at hips to ~45 degrees, slight knee bend",
            "Grip bar shoulder-width, arms hanging straight",
            "Pull bar to lower chest / upper abdomen",
            "Squeeze shoulder blades together at the top",
            "Lower with control, full arm extension",
        ],
        "muscle_groups": ["back", "biceps", "rear delts"],
        "common_mistakes": [
            "Using momentum to swing the weight up",
            "Standing too upright",
            "Not squeezing at the top",
            "Rounding the lower back",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["barbell"],
        "calories_per_min": 7.0,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "upper_body"],
    },
    {
        "name": "Pull-up",
        "description": "Bodyweight vertical pulling exercise.",
        "instructions_json": [
            "Grip the bar slightly wider than shoulder width",
            "Hang with arms fully extended, engage lats",
            "Pull yourself up until chin clears the bar",
            "Lower with control to full hang",
            "Avoid swinging or kipping",
        ],
        "muscle_groups": ["back", "biceps", "forearms"],
        "common_mistakes": [
            "Not using full range of motion",
            "Kipping or swinging for momentum",
            "Shrugging shoulders up instead of pulling with lats",
            "Crossing legs behind (reduces core engagement)",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["pull-up bar"],
        "calories_per_min": 7.5,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "upper_body", "bodyweight"],
    },
    {
        "name": "Lat Pulldown",
        "description": "Cable machine exercise for back width.",
        "instructions_json": [
            "Sit at lat pulldown machine, grip bar wide",
            "Lean back slightly, chest up",
            "Pull bar down to upper chest",
            "Squeeze lats at the bottom",
            "Return bar slowly to full arm extension",
        ],
        "muscle_groups": ["back", "biceps"],
        "common_mistakes": [
            "Pulling behind the neck (injury risk)",
            "Leaning too far back",
            "Using arms more than lats",
            "Not controlling the weight on the way up",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif",
        "difficulty": "beginner",
        "equipment_needed": ["lat pulldown machine"],
        "calories_per_min": 5.5,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "upper_body"],
    },
    {
        "name": "Dumbbell Row",
        "description": "Single-arm rowing movement for back development.",
        "instructions_json": [
            "Place one knee and hand on bench for support",
            "Hold dumbbell in free hand, arm hanging straight",
            "Pull dumbbell to hip, leading with elbow",
            "Squeeze shoulder blade back at the top",
            "Lower with control to full stretch",
        ],
        "muscle_groups": ["back", "biceps", "rear delts"],
        "common_mistakes": [
            "Rotating the torso to lift the weight",
            "Not pulling high enough (to hip, not chest)",
            "Using momentum instead of controlled reps",
            "Rounding the supporting shoulder",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbell", "bench"],
        "calories_per_min": 5.0,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "upper_body"],
    },
    {
        "name": "Deadlift",
        "description": "Full-body compound lift targeting the posterior chain.",
        "instructions_json": [
            "Stand with feet hip-width apart, bar over mid-foot",
            "Hinge at hips, grip bar just outside knees",
            "Flatten back, brace core, chest up",
            "Drive through floor, extending hips and knees together",
            "Lock out at top with shoulders back",
        ],
        "muscle_groups": ["back", "hamstrings", "glutes", "core", "forearms"],
        "common_mistakes": [
            "Rounding the lower back",
            "Starting with hips too low (it's not a squat)",
            "Jerking the bar off the floor",
            "Hyperextending at the top",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif",
        "difficulty": "advanced",
        "equipment_needed": ["barbell"],
        "calories_per_min": 9.0,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "full_body", "legs_core"],
    },
    {
        "name": "Face Pull",
        "description": "Cable exercise for rear delts and rotator cuff health.",
        "instructions_json": [
            "Set cable at upper chest height with rope attachment",
            "Grip rope with thumbs pointing back",
            "Pull toward face, separating the rope ends",
            "Externally rotate at the end, hands beside ears",
            "Squeeze rear delts, then return with control",
        ],
        "muscle_groups": ["rear delts", "traps", "rotator cuff"],
        "common_mistakes": [
            "Setting the cable too low",
            "Not externally rotating at the end",
            "Using too much weight",
            "Pulling to the chest instead of the face",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif",
        "difficulty": "beginner",
        "equipment_needed": ["cable machine", "rope attachment"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep", "push", "upper_body"],
    },
    {
        "name": "Seated Cable Row",
        "description": "Horizontal cable pull for mid-back thickness.",
        "instructions_json": [
            "Sit at cable row station, feet on pads, slight knee bend",
            "Grip the handle, sit upright with back straight",
            "Pull handle to lower chest, elbows close to body",
            "Squeeze shoulder blades together hard",
            "Return slowly with arms fully extended",
        ],
        "muscle_groups": ["back", "biceps", "rear delts"],
        "common_mistakes": [
            "Jerking backward to initiate the pull",
            "Rounding the back",
            "Not squeezing at the top",
            "Using too narrow a rep range",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif",
        "difficulty": "beginner",
        "equipment_needed": ["cable machine"],
        "calories_per_min": 5.0,
        "exercise_type": "compound",
        "split_tags": ["pull", "back_bicep", "upper_body"],
    },
    {
        "name": "Straight-Arm Pulldown",
        "description": "Cable isolation for the lats — arms stay straight.",
        "instructions_json": [
            "Stand at cable machine, high pulley, bar or rope attachment",
            "Keep arms straight with slight elbow bend",
            "Pull bar down to hip level in a sweeping arc",
            "Squeeze lats hard at the bottom",
            "Return slowly, full stretch overhead",
        ],
        "muscle_groups": ["back", "lats"],
        "common_mistakes": [
            "Bending elbows and turning it into a pulldown",
            "Using momentum",
            "Not feeling the lats — think 'push the bar to your pockets'",
            "Leaning too far forward",
        ],
        "image_url": "https://burnfit.io/en/wp-content/uploads/sites/3/2026/01/CABLE_ARM_PULL_DOWN.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["cable machine"],
        "calories_per_min": 4.5,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep"],
    },
    # ─── SHOULDERS ───────────────────────────────────────────────────────────
    {
        "name": "Overhead Press",
        "description": "Standing shoulder press with a barbell.",
        "instructions_json": [
            "Start with bar at shoulder height, grip just outside shoulders",
            "Brace core and squeeze glutes",
            "Press bar straight overhead",
            "Move head slightly forward once bar passes forehead",
            "Lock out arms fully at the top",
        ],
        "muscle_groups": ["shoulders", "triceps", "core"],
        "common_mistakes": [
            "Excessive lower back arch",
            "Pressing the bar forward instead of straight up",
            "Not bracing the core",
            "Using leg drive (unless doing push press)",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Shoulder-Press.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["barbell"],
        "calories_per_min": 6.5,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder", "upper_body"],
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "Seated or standing overhead press with dumbbells.",
        "instructions_json": [
            "Hold dumbbells at shoulder height, palms forward",
            "Press straight up until arms are fully extended",
            "Lower with control back to shoulder level",
            "Keep core braced throughout",
            "Don't lean back excessively",
        ],
        "muscle_groups": ["shoulders", "triceps"],
        "common_mistakes": [
            "Arching the lower back",
            "Not pressing straight up",
            "Using momentum from legs",
            "Not going through full range of motion",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 5.5,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder", "upper_body"],
    },
    {
        "name": "Lateral Raise",
        "description": "Isolation exercise for the side deltoids.",
        "instructions_json": [
            "Stand holding dumbbells at your sides",
            "Slight bend in elbows, palms facing inward",
            "Raise arms out to the sides until parallel with floor",
            "Lead with elbows, not hands",
            "Lower slowly with control",
        ],
        "muscle_groups": ["shoulders"],
        "common_mistakes": [
            "Using too much weight and swinging",
            "Raising above shoulder height (causes impingement)",
            "Shrugging the traps instead of isolating delts",
            "Straight arms (slight bend protects joints)",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
    },
    {
        "name": "Rear Delt Fly",
        "description": "Isolation for the rear deltoids and upper back.",
        "instructions_json": [
            "Bend forward 45-90 degrees at the hips",
            "Hold dumbbells hanging below chest",
            "Raise arms out to the sides, leading with elbows",
            "Squeeze rear delts at the top",
            "Lower slowly, feel the stretch",
        ],
        "muscle_groups": ["rear delts", "upper back"],
        "common_mistakes": [
            "Using too much weight and swinging",
            "Raising arms too high (becomes a shrug)",
            "Not keeping a neutral spine",
            "Speed-repping without contraction",
        ],
        "image_url": "https://pelank.com/wp-content/uploads/2025/01/Dumbbell-Reverse-Fly.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep", "chest_shoulder"],
    },
    {
        "name": "Arnold Press",
        "description": "Dumbbell press with rotation for full shoulder development.",
        "instructions_json": [
            "Hold dumbbells at chest height, palms facing you",
            "As you press up, rotate palms forward",
            "At the top arms are fully extended, palms away from you",
            "Reverse rotation as you lower back to start",
            "Pause briefly at the bottom",
        ],
        "muscle_groups": ["shoulders", "triceps"],
        "common_mistakes": [
            "Going too fast and losing control of the rotation",
            "Not fully rotating at the top",
            "Excessive back arch",
            "Not controlling the negative",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Arnold-Press.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 5.0,
        "exercise_type": "compound",
        "split_tags": ["push", "chest_shoulder"],
    },
    # ─── ARMS ────────────────────────────────────────────────────────────────
    {
        "name": "Dumbbell Curl",
        "description": "Isolation exercise for the biceps.",
        "instructions_json": [
            "Stand with a dumbbell in each hand, arms at sides",
            "Keep elbows pinned to your sides throughout",
            "Curl the weights up while supinating the wrist",
            "Squeeze at the top, then lower with control",
            "Alternate arms or do both simultaneously",
        ],
        "muscle_groups": ["biceps", "forearms"],
        "common_mistakes": [
            "Swinging the body for momentum",
            "Moving elbows forward during the curl",
            "Going too heavy and sacrificing form",
            "Not controlling the negative portion",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep"],
    },
    {
        "name": "Incline Dumbbell Curl",
        "description": "Bicep curl with full stretch at bottom on incline bench.",
        "instructions_json": [
            "Set bench to 45-60 degree incline, sit back against it",
            "Let arms hang freely, dumbbells at full extension",
            "Curl up slowly without moving upper arms",
            "Squeeze at top, control the lowering phase",
            "Feel the full stretch at the bottom",
        ],
        "muscle_groups": ["biceps"],
        "common_mistakes": [
            "Shortening the range to avoid the stretch",
            "Swinging forward off the bench",
            "Using too much weight",
            "Too fast on the negative",
        ],
        "image_url": "https://burnfit.io/en/wp-content/uploads/sites/3/2026/01/INC_DB_CURL.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["dumbbells", "adjustable bench"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep"],
    },
    {
        "name": "Hammer Curl",
        "description": "Neutral grip curl targeting brachialis and forearms.",
        "instructions_json": [
            "Hold dumbbells at sides with neutral grip (thumbs up)",
            "Keep elbows fixed at sides",
            "Curl up without rotating the wrist",
            "Lower with control",
            "Both arms simultaneously or alternating",
        ],
        "muscle_groups": ["biceps", "brachialis", "forearms"],
        "common_mistakes": [
            "Rotating the wrists during the movement",
            "Swinging for momentum",
            "Not going full range of motion",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep"],
    },
    {
        "name": "EZ Bar Curl",
        "description": "Barbell curl with angled grip — easier on wrists.",
        "instructions_json": [
            "Grip EZ bar at the angled grips, shoulder-width",
            "Stand upright, elbows at sides",
            "Curl bar to shoulder height",
            "Lower slowly to full extension",
            "No body swing",
        ],
        "muscle_groups": ["biceps", "forearms"],
        "common_mistakes": [
            "Swinging upper body",
            "Partial reps",
            "Elbows drifting forward",
        ],
        "image_url": "https://burnfit.io/en/wp-content/uploads/sites/3/2026/01/EZB_CURL.gif",
        "difficulty": "beginner",
        "equipment_needed": ["EZ bar"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["pull", "back_bicep"],
    },
    {
        "name": "Tricep Pushdown",
        "description": "Cable isolation exercise for the triceps.",
        "instructions_json": [
            "Stand at cable machine with rope or bar attachment",
            "Grip the attachment, elbows pinned at your sides",
            "Push down until arms are fully extended",
            "Squeeze the triceps at the bottom",
            "Return slowly to starting position (forearms ~90 degrees)",
        ],
        "muscle_groups": ["triceps"],
        "common_mistakes": [
            "Letting elbows drift forward",
            "Leaning over the weight",
            "Using momentum from the shoulders",
            "Not fully extending at the bottom",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif",
        "difficulty": "beginner",
        "equipment_needed": ["cable machine"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
    },
    {
        "name": "Overhead Tricep Extension",
        "description": "Long head tricep isolation with dumbbells or EZ bar.",
        "instructions_json": [
            "Hold one dumbbell with both hands or EZ bar above head",
            "Elbows pointing forward, tucked close to head",
            "Lower the weight behind your head until forearms are parallel",
            "Push back up to full extension",
            "Keep upper arms still — only forearms move",
        ],
        "muscle_groups": ["triceps"],
        "common_mistakes": [
            "Elbows flaring out wide",
            "Upper arms moving during the lift",
            "Not going deep enough",
            "Too heavy causing shoulder strain",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Triceps-Extension.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbell"],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
    },
    {
        "name": "Skull Crusher",
        "description": "Lying tricep extension with EZ bar.",
        "instructions_json": [
            "Lie on bench holding EZ bar with narrow grip above chest",
            "Lower bar toward forehead by bending elbows only",
            "Upper arms stay vertical, pointed toward ceiling",
            "Extend arms back to full lockout",
            "Control the weight — no bouncing",
        ],
        "muscle_groups": ["triceps"],
        "common_mistakes": [
            "Upper arms drifting backward as you lower",
            "Too fast on the negative (skull crush risk)",
            "Too wide a grip",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Dumbbell-Skull-Crusher.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["EZ bar", "bench"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["push", "chest_shoulder"],
    },
    # ─── LEGS ─────────────────────────────────────────────────────────────────
    {
        "name": "Squat",
        "description": "Fundamental compound lower body exercise.",
        "instructions_json": [
            "Position bar on upper traps, feet shoulder-width apart",
            "Brace core and begin descent by pushing hips back",
            "Lower until thighs are at least parallel to floor",
            "Drive through heels to stand back up",
            "Keep chest up and knees tracking over toes",
        ],
        "muscle_groups": ["quadriceps", "glutes", "hamstrings", "core"],
        "common_mistakes": [
            "Knees caving inward",
            "Leaning too far forward",
            "Not hitting depth (parallel)",
            "Rising on toes instead of driving through heels",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Back-Squat.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["barbell", "squat rack"],
        "calories_per_min": 8.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Romanian Deadlift",
        "description": "Hip hinge movement targeting hamstrings and glutes.",
        "instructions_json": [
            "Hold barbell with overhand grip at hip height",
            "Slight bend in knees, keep this angle fixed",
            "Hinge at hips, pushing them back",
            "Lower bar along legs until you feel hamstring stretch",
            "Drive hips forward to return to standing",
        ],
        "muscle_groups": ["hamstrings", "glutes", "lower back"],
        "common_mistakes": [
            "Bending the knees too much (turns into a squat)",
            "Rounding the back",
            "Not hinging enough at the hips",
            "Looking up (keep neutral neck)",
        ],
        "image_url": "https://burnfit.io/en/wp-content/uploads/sites/3/2026/01/RM_BB_DL.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["barbell"],
        "calories_per_min": 7.0,
        "exercise_type": "compound",
        "split_tags": ["legs_core", "pull"],
    },
    {
        "name": "Leg Press",
        "description": "Machine compound exercise for legs.",
        "instructions_json": [
            "Sit in the leg press with feet shoulder-width on platform",
            "Unrack and lower the platform by bending knees",
            "Lower until knees are at ~90 degrees",
            "Press through heels to extend legs",
            "Don't lock out knees completely at the top",
        ],
        "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
        "common_mistakes": [
            "Placing feet too high or too low on platform",
            "Letting hips come off the seat pad",
            "Locking out knees fully",
            "Using too short a range of motion",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif",
        "difficulty": "beginner",
        "equipment_needed": ["leg press machine"],
        "calories_per_min": 6.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Bulgarian Split Squat",
        "description": "Unilateral leg press for quads and glutes, fixes imbalances.",
        "instructions_json": [
            "Stand ~2 feet in front of a bench, rear foot elevated on bench",
            "Front foot far enough forward so shin stays vertical",
            "Lower rear knee toward floor",
            "Drive up through front heel",
            "Keep torso upright, don't lean forward",
        ],
        "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
        "common_mistakes": [
            "Front foot too close (excessive forward knee travel)",
            "Leaning too far forward",
            "Knee caving inward on the working leg",
            "Rushing the movement",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/05/Dumbbell-Bulgarian-Split-Squat.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["bench", "dumbbells"],
        "calories_per_min": 8.0,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Hip Thrust",
        "description": "Glute-focused exercise using a bench and barbell.",
        "instructions_json": [
            "Sit on floor with upper back against bench",
            "Roll barbell over hips (use pad for comfort)",
            "Feet flat on floor, shoulder-width apart",
            "Drive hips up until body forms a straight line",
            "Squeeze glutes at top, lower with control",
        ],
        "muscle_groups": ["glutes", "hamstrings"],
        "common_mistakes": [
            "Hyperextending the lower back at the top",
            "Pushing through toes instead of heels",
            "Not squeezing glutes at the top",
            "Placing feet too close or too far from body",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif",
        "difficulty": "intermediate",
        "equipment_needed": ["barbell", "bench"],
        "calories_per_min": 6.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Leg Curl",
        "description": "Machine isolation for hamstrings.",
        "instructions_json": [
            "Lie face down or sit in the leg curl machine",
            "Adjust pad to rest just above ankles",
            "Curl legs up, squeezing hamstrings",
            "Hold briefly at the top",
            "Lower with control, don't let the weight slam",
        ],
        "muscle_groups": ["hamstrings"],
        "common_mistakes": [
            "Using momentum to swing the weight",
            "Lifting hips off the pad",
            "Not going through full range of motion",
            "Going too heavy and losing control",
        ],
        "image_url": "https://burnfit.io/wp-content/uploads/LEG_CURL.gif",
        "difficulty": "beginner",
        "equipment_needed": ["leg curl machine"],
        "calories_per_min": 4.5,
        "exercise_type": "isolation",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Leg Extension",
        "description": "Quad isolation on the machine.",
        "instructions_json": [
            "Sit in leg extension machine, pad resting on shins",
            "Extend legs to full lockout",
            "Squeeze quads hard at the top for 1 second",
            "Lower slowly — don't let weight slam",
            "Full range: start with knees at 90 degrees",
        ],
        "muscle_groups": ["quadriceps"],
        "common_mistakes": [
            "Not going through full range of motion",
            "Using momentum to kick up",
            "Skipping the squeeze at the top",
            "Dropping weight too fast",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/LEG-EXTENSION.gif",
        "difficulty": "beginner",
        "equipment_needed": ["leg extension machine"],
        "calories_per_min": 4.0,
        "exercise_type": "isolation",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Calf Raise",
        "description": "Standing calf raise for gastrocnemius development.",
        "instructions_json": [
            "Stand on edge of step or flat ground",
            "Rise up on toes as high as possible",
            "Hold for 1 second at the peak",
            "Lower slowly to full stretch below flat",
            "Feel the stretch, then drive back up",
        ],
        "muscle_groups": ["calves"],
        "common_mistakes": [
            "Bouncing at the bottom (no stretch)",
            "Partial range of motion",
            "Going too fast",
            "Not using a slow negative",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Calf-Raise.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 3.5,
        "exercise_type": "isolation",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Walking Lunge",
        "description": "Dynamic unilateral leg exercise for quads and glutes.",
        "instructions_json": [
            "Stand tall holding dumbbells at sides",
            "Step forward and lower back knee toward ground",
            "Front knee stays above ankle — don't let it cave",
            "Push off front foot to bring rear leg forward into next lunge",
            "Keep torso upright throughout",
        ],
        "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
        "common_mistakes": [
            "Knee caving inward",
            "Front knee going past toes",
            "Leaning too far forward",
            "Rushing and losing balance",
        ],
        "image_url": "https://gymvisual.com/img/p/2/1/6/7/3/21673.gif",
        "difficulty": "beginner",
        "equipment_needed": ["dumbbells"],
        "calories_per_min": 7.0,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Front Squat",
        "description": "Barbell squat with bar in front — more quad emphasis.",
        "instructions_json": [
            "Hold bar in front rack (on shoulders, elbows high)",
            "Feet shoulder-width, toes slightly out",
            "Squat deep keeping torso very upright",
            "Drive up through heels",
            "Keep elbows high throughout",
        ],
        "muscle_groups": ["quadriceps", "glutes", "core"],
        "common_mistakes": [
            "Elbows dropping (bar falls forward)",
            "Upper back rounding",
            "Heels rising off floor",
            "Caving knees",
        ],
        "image_url": "https://www.kettlebellkings.com/cdn/shop/articles/Front_Squats.gif?v=1694617488",
        "difficulty": "advanced",
        "equipment_needed": ["barbell", "squat rack"],
        "calories_per_min": 9.0,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    # ─── CORE ─────────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "description": "Isometric core exercise.",
        "instructions_json": [
            "Start in push-up position on forearms",
            "Keep body in a straight line from head to heels",
            "Engage core by pulling belly button toward spine",
            "Keep hips level — don't sag or pike",
            "Hold for prescribed time, breathing steadily",
        ],
        "muscle_groups": ["core", "shoulders"],
        "common_mistakes": [
            "Hips sagging toward the floor",
            "Piking hips up too high",
            "Holding breath",
            "Looking up (keep neck neutral)",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/04/Weighted-Front-Plank.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 3.5,
        "exercise_type": "isometric",
        "split_tags": ["legs_core", "full_body"],
    },
    {
        "name": "Ab Wheel Rollout",
        "description": "Full core extension exercise with ab wheel.",
        "instructions_json": [
            "Kneel on floor holding ab wheel handle with both hands",
            "Roll wheel forward as far as you can while keeping core tight",
            "Lower body toward floor in a controlled arc",
            "Engage core to pull wheel back to starting position",
            "Don't let lower back sag",
        ],
        "muscle_groups": ["core", "lats", "shoulders"],
        "common_mistakes": [
            "Lower back sagging (core collapse)",
            "Going too far before having the strength",
            "Holding breath",
            "Rushing on the way back",
        ],
        "image_url": "https://i.pinimg.com/originals/81/c6/ac/81c6ac9bf4e3de344451a42286cb89be.gif",
        "difficulty": "advanced",
        "equipment_needed": ["ab wheel"],
        "calories_per_min": 5.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Hanging Leg Raise",
        "description": "Lower ab and hip flexor exercise hanging from bar.",
        "instructions_json": [
            "Hang from pull-up bar with straight arms",
            "Keep legs straight or slightly bent",
            "Raise legs to hip height or higher",
            "Lower slowly — don't swing",
            "Engage core the whole time; don't use momentum",
        ],
        "muscle_groups": ["core", "hip flexors"],
        "common_mistakes": [
            "Swinging for momentum",
            "Bending knees too much to compensate for weak core",
            "Dropping legs too fast",
            "Not controlling the bottom position",
        ],
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8utiwzsn11noMd8sH0r3jjZa1647Q7xAA6w&s",
        "difficulty": "intermediate",
        "equipment_needed": ["pull-up bar"],
        "calories_per_min": 5.0,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Russian Twist",
        "description": "Rotational core exercise for obliques.",
        "instructions_json": [
            "Sit on floor, knees bent, lean back 45 degrees",
            "Hold weight plate or dumbbell in front of chest",
            "Rotate torso to one side, then the other",
            "Keep core braced and feet off the floor for added difficulty",
            "Controlled rotation — not speed",
        ],
        "muscle_groups": ["core", "obliques"],
        "common_mistakes": [
            "Speed-repping without rotation control",
            "Feet not elevated (easier, not wrong)",
            "Twisting too far with a heavy weight",
            "Rounding the lower back",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/02/Russian-Twist.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 4.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    {
        "name": "Dead Bug",
        "description": "Anti-extension core stability exercise.",
        "instructions_json": [
            "Lie on back, arms extended toward ceiling, knees at 90 degrees",
            "Slowly lower opposite arm and leg toward floor simultaneously",
            "Keep lower back pressed to floor the entire time",
            "Return to start and repeat on the other side",
            "Exhale as you lower, inhale as you return",
        ],
        "muscle_groups": ["core", "hip flexors"],
        "common_mistakes": [
            "Lower back lifting off the floor",
            "Going too fast",
            "Not bracing core before moving",
            "Arms and legs not reaching full extension",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/05/Dead-Bug.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 3.0,
        "exercise_type": "isometric",
        "split_tags": ["legs_core", "full_body"],
    },
    {
        "name": "Glute Bridge",
        "description": "Hip extension exercise activating glutes.",
        "instructions_json": [
            "Lie on back with knees bent, feet flat on floor",
            "Drive hips up by squeezing glutes hard",
            "Body forms a straight line from shoulders to knees",
            "Hold at the top for 2 seconds",
            "Lower slowly and repeat",
        ],
        "muscle_groups": ["glutes", "hamstrings", "core"],
        "common_mistakes": [
            "Not squeezing glutes — using lower back instead",
            "Hyperextending at the top",
            "Feet too close or too far",
            "Dropping too fast",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2022/02/Banded-Glute-Bridge.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 3.5,
        "exercise_type": "compound",
        "split_tags": ["legs_core"],
    },
    # ─── CARDIO / WARMUP ────────────────────────────────────────────────────
    {
        "name": "Jump Rope",
        "description": "High-intensity cardio warmup.",
        "instructions_json": [
            "Hold handles lightly, rotate from wrists not arms",
            "Land softly on balls of feet, slight knee bend",
            "Stay on toes, keep jumps small and efficient",
            "Keep elbows close to body",
            "Start at a steady pace for warmup",
        ],
        "muscle_groups": ["calves", "core", "shoulders"],
        "common_mistakes": [
            "Landing flat-footed",
            "Jumping too high",
            "Arms too wide",
            "Tense shoulders",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2023/10/Skip-Jump-Rope.gif",
        "difficulty": "beginner",
        "equipment_needed": ["jump rope"],
        "calories_per_min": 12.0,
        "exercise_type": "cardio",
        "split_tags": ["full_body", "cardio"],
    },
    {
        "name": "Burpee",
        "description": "Full-body explosive cardio exercise.",
        "instructions_json": [
            "Stand, then drop hands to floor",
            "Jump feet back to push-up position",
            "Perform a push-up",
            "Jump feet back to hands",
            "Explode up and jump with arms overhead",
        ],
        "muscle_groups": ["full body", "core", "chest", "quadriceps"],
        "common_mistakes": [
            "Skipping the push-up",
            "Landing with stiff knees",
            "Sagging core in the plank position",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/10/Jack-Burpees.gif",
        "difficulty": "intermediate",
        "equipment_needed": [],
        "calories_per_min": 12.5,
        "exercise_type": "cardio",
        "split_tags": ["full_body", "cardio", "bodyweight"],
    },
    {
        "name": "Mountain Climber",
        "description": "Core and cardio exercise from plank position.",
        "instructions_json": [
            "Start in high plank position",
            "Drive one knee toward chest",
            "Alternate rapidly, maintaining stable plank",
            "Keep hips level — don't pike or sag",
            "Breathe steadily throughout",
        ],
        "muscle_groups": ["core", "hip flexors", "shoulders"],
        "common_mistakes": [
            "Hips rising too high",
            "Bouncing — stay stable in the upper body",
            "Looking up (neutral neck)",
        ],
        "image_url": "https://burnfit.io/en/wp-content/uploads/sites/3/2026/01/MOUNT_CLIMB.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 10.0,
        "exercise_type": "cardio",
        "split_tags": ["full_body", "cardio", "legs_core"],
    },
    # ─── STRETCHES / MOBILITY ────────────────────────────────────────────────
    {
        "name": "Hip Flexor Stretch",
        "description": "Kneeling lunge stretch to fix anterior pelvic tilt.",
        "instructions_json": [
            "Kneel on one knee, other foot forward",
            "Push hips forward gently until you feel stretch in front of rear hip",
            "Keep torso upright, don't arch lower back",
            "Hold for 45 seconds each side",
            "Breathe slowly and deepen the stretch on exhale",
        ],
        "muscle_groups": ["hip flexors", "quadriceps"],
        "common_mistakes": [
            "Arching lower back (not a true hip flexor stretch)",
            "Not pushing hips far enough forward",
            "Holding breath",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/08/Kneeling-Hip-Flexor-Stretch.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 2.0,
        "exercise_type": "stretch",
        "split_tags": ["legs_core", "full_body"],
    },
    {
        "name": "Doorway Chest Stretch",
        "description": "Opens chest and corrects rounded shoulders.",
        "instructions_json": [
            "Stand in doorway, arms bent 90 degrees on the frame",
            "Step forward slowly until chest opens and you feel the stretch",
            "Hold 30-45 seconds",
            "Keep lower back neutral, don't arch",
            "Breathe deeply into the chest",
        ],
        "muscle_groups": ["chest", "shoulders", "biceps"],
        "common_mistakes": [
            "Arching lower back",
            "Arms too high (shoulder impingement risk)",
            "Not stepping far enough through",
        ],
        "image_url": "https://gymvisual.com/img/p/3/2/8/3/7/32837.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 1.5,
        "exercise_type": "stretch",
        "split_tags": ["full_body"],
    },
    {
        "name": "Chin Tuck",
        "description": "Corrects forward head posture — do it 10x per day.",
        "instructions_json": [
            "Sit or stand upright",
            "Pull chin straight back (creating a double chin)",
            "Hold for 5 seconds",
            "Release and repeat",
            "10 reps × 3 sets throughout the day",
        ],
        "muscle_groups": ["neck", "upper back"],
        "common_mistakes": [
            "Tilting head up or down instead of pulling straight back",
            "Not holding long enough",
            "Shrugging shoulders",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Chin-Tuck.gif",
        "difficulty": "beginner",
        "equipment_needed": [],
        "calories_per_min": 1.0,
        "exercise_type": "stretch",
        "split_tags": ["full_body"],
    },
    {
        "name": "Band Pull-Apart",
        "description": "Resistance band drill for rear delts and posture.",
        "instructions_json": [
            "Hold resistance band at shoulder height in front of you",
            "Arms straight, shoulder-width grip",
            "Pull band apart horizontally until arms are fully extended to sides",
            "Squeeze shoulder blades together at the end",
            "Return slowly, maintaining tension",
        ],
        "muscle_groups": ["rear delts", "upper back", "rotator cuff"],
        "common_mistakes": [
            "Bending elbows",
            "Shrugging shoulders",
            "Going too fast without the squeeze",
        ],
        "image_url": "https://fitnessprogramer.com/wp-content/uploads/2021/06/Band-pull-apart.gif",
        "difficulty": "beginner",
        "equipment_needed": ["resistance band"],
        "calories_per_min": 3.0,
        "exercise_type": "isolation",
        "split_tags": ["full_body", "pull"],
    },
]

# ─── Backfill: ensure ≥6 exercises per muscle group ─────────────────────────
# Compact entries — only the fields the seeder reads directly. Enrichment is
# applied in the loop below from `ENRICHMENT` when available.

def _compact(name, desc, muscle_groups, image_url, equipment, *,
             difficulty="beginner", instructions=None, mistakes=None,
             calories_per_min=4.0, exercise_type="isolation",
             split_tags=None):
    return {
        "name": name,
        "description": desc,
        "instructions_json": instructions or [
            "Set up with proper form, stable base, neutral spine",
            "Move through the full range of motion under control",
            "Squeeze the target muscle on the contraction",
            "Lower with control over 2–3 seconds",
        ],
        "muscle_groups": muscle_groups,
        "common_mistakes": mistakes or [
            "Going too heavy and losing form",
            "Cutting the range of motion short",
            "Using momentum instead of muscle",
        ],
        "image_url": image_url,
        "difficulty": difficulty,
        "equipment_needed": equipment,
        "calories_per_min": calories_per_min,
        "exercise_type": exercise_type,
        "split_tags": split_tags or [],
    }


SEED_EXERCISES.extend([
    # ── Chest backfill ──────────────────────────────────────────────────────
    _compact("Machine Chest Press",
             "Plate-loaded chest press machine — safer learning curve than barbell.",
             ["chest", "shoulders", "triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Chest-Press-Machine.gif",
             ["machine"], split_tags=["push", "chest_shoulder"], exercise_type="compound",
             calories_per_min=5.5),

    # ── Biceps backfill ─────────────────────────────────────────────────────
    _compact("Concentration Curl",
             "Single-arm seated curl with elbow braced on inner thigh.",
             ["biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif",
             ["dumbbell"], split_tags=["pull", "arm"]),
    _compact("Cable Bicep Curl",
             "Constant-tension curl using a low pulley.",
             ["biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Cable-Bicep-Curl.gif",
             ["cable"], split_tags=["pull", "arm"]),

    # ── Triceps backfill ────────────────────────────────────────────────────
    _compact("Close-Grip Bench Press",
             "Compound triceps builder with bar held shoulder-width.",
             ["triceps", "chest", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Close-Grip-Bench-Press.gif",
             ["barbell", "bench"], difficulty="intermediate", exercise_type="compound",
             split_tags=["push", "arm"], calories_per_min=6.0),
    _compact("Tricep Dip",
             "Bodyweight triceps dip on bench or parallel bars.",
             ["triceps", "chest", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bench-Dips.gif",
             ["bench"], split_tags=["push", "arm"], exercise_type="compound"),
    _compact("Rope Tricep Extension",
             "Cable rope extension overhead — long-head focused.",
             ["triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Cable-Overhead-Triceps-Extension.gif",
             ["cable"], split_tags=["push", "arm"]),

    # ── Abs backfill ────────────────────────────────────────────────────────
    _compact("Cable Crunch",
             "Kneeling cable crunch — heavy weighted abs work.",
             ["abs", "core"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Kneeling-Cable-Crunch.gif",
             ["cable"], split_tags=["core"]),
    _compact("Bicycle Crunch",
             "Alternating elbow-to-knee crunch for obliques.",
             ["abs", "obliques"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bicycle-Crunch.gif",
             [], split_tags=["core"]),

    # ── Calves backfill ─────────────────────────────────────────────────────
    _compact("Standing Calf Raise", "Standing single- or two-legged calf raise on a step.",
             ["calves"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Standing-Calf-Raise.gif", [], split_tags=["legs"]),
    _compact("Seated Calf Raise", "Seated machine raise — soleus emphasis.",
             ["calves"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Calf-Raise.gif", ["machine"], split_tags=["legs"]),
    _compact("Donkey Calf Raise", "Loaded calf raise bent at hips — full stretch.",
             ["calves"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Donkey-Calf-Raise.gif", ["machine"], split_tags=["legs"]),
    _compact("Smith Machine Calf Raise", "Smith machine with toes on plate for safe loading.",
             ["calves"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Standing-Calf-Raise.gif", ["machine"], split_tags=["legs"]),
    _compact("Single-Leg Calf Raise", "Bodyweight single-leg raise — fixes side-to-side imbalance.",
             ["calves"], "https://fitnessprogramer.com/wp-content/uploads/2021/09/Single-Leg-Calf-Raise.gif", [], split_tags=["legs"]),

    # ── Neck backfill ───────────────────────────────────────────────────────
    _compact("Plate Neck Curl",
             "Lie on back, plate on forehead, flex neck up — light weight.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2021/10/Neck-Curl.gif",
             ["plate"], difficulty="beginner",
             instructions=[
                 "Lie face-up on a bench with head off the edge",
                 "Hold a small plate (1.25-2.5kg) on the forehead with a towel",
                 "Tuck chin and curl the neck up slowly over 2 seconds",
                 "Pause and lower under control over 3 seconds",
             ],
             split_tags=["neck"]),
    _compact("Plate Neck Extension", "Lie face-down, plate on back of head, extend neck.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2021/10/Neck-Extension.gif", ["plate"], split_tags=["neck"]),
    _compact("Neck Side Flexion", "Side-lying neck raise to strengthen the lateral neck.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2021/10/Lateral-Neck-Flexion.gif", ["plate"], split_tags=["neck"]),
    _compact("Neck Harness", "4-way neck training using a head harness with chain.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2022/04/Neck-Harness.gif", ["harness"], difficulty="intermediate", split_tags=["neck"]),
    _compact("Resistance Band Neck Press", "Light resistance band pressed against forehead/back of head.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2021/10/Neck-Flexion-With-Resistance-Band.gif", ["resistance band"], split_tags=["neck"]),
    _compact("Manual Resistance Neck", "Press hand against forehead — isometric, no equipment.",
             ["neck"], "https://fitnessprogramer.com/wp-content/uploads/2021/10/Manual-Neck-Flexion.gif", [], exercise_type="isometric", split_tags=["neck"]),

    # ── Forearms backfill ───────────────────────────────────────────────────
    _compact("Wrist Curl", "Forearm flexor curl — forearms on bench, palms up.",
             ["forearms"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Wrist-Curl.gif", ["dumbbell"], split_tags=["arm"]),
    _compact("Reverse Wrist Curl", "Forearm extensor curl — palms down, smaller weight.",
             ["forearms"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Reverse-Wrist-Curl.gif",
             ["dumbbell"], split_tags=["arm"]),
    _compact("Farmer's Carry", "Heavy walks with dumbbells — grip + traps + core.",
             ["forearms", "traps", "core"], "https://fitnessprogramer.com/wp-content/uploads/2021/06/Farmers-Walk.gif", ["dumbbell"],
             exercise_type="compound", split_tags=["full_body"], calories_per_min=7.0),
    _compact("Plate Pinch", "Pinch two plates together for time — pure grip strength.",
             ["forearms"], "https://fitnessprogramer.com/wp-content/uploads/2023/01/Plate-Pinch.gif", ["plate"], exercise_type="isometric", split_tags=["arm"]),
    _compact("Dead Hang", "Hang from a pull-up bar for time — grip and decompression.",
             ["forearms", "lats"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dead-Hang.gif", ["pull-up bar"],
             exercise_type="isometric", split_tags=["pull"]),
    _compact("Towel Pull-up Hang", "Hang from a towel over the bar — brutal grip work.",
             ["forearms", "lats"], "https://fitnessprogramer.com/wp-content/uploads/2021/06/Towel-Pull-Up.gif", ["pull-up bar", "towel"],
             difficulty="advanced", exercise_type="isometric", split_tags=["pull"]),

    # ── Rear delts backfill ─────────────────────────────────────────────────
    _compact("Reverse Pec Deck", "Machine reverse fly — isolated rear delt work.",
             ["rear delts", "upper back"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Reverse-Fly-Machine.gif", ["machine"], split_tags=["pull"]),
    _compact("Bent-over Reverse Fly", "Bent-over dumbbell fly — pinch shoulder blades.",
             ["rear delts", "upper back"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Bent-Over-Reverse-Fly.gif", ["dumbbell"], split_tags=["pull"]),
    _compact("Cable Reverse Fly", "Standing cable cross-body reverse fly.",
             ["rear delts"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Cable-Crossover-Reverse-Fly.gif", ["cable"], split_tags=["pull"]),
    _compact("Wide-Grip Upright Row",
             "Wide-grip row to chest — rear delts + traps without impingement risk.",
             ["rear delts", "traps", "shoulders"], "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Upright-Row.gif",
             ["barbell"], difficulty="intermediate", split_tags=["pull"]),

    # ── Chest expansion (targeting 12 total) ────────────────────────────────
    _compact("Dips (Chest Focus)",
             "Forward-leaning dip — emphasises lower chest over triceps.",
             ["chest", "triceps", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Chest-Dip.gif",
             ["dip bar"], exercise_type="compound", split_tags=["push", "chest_shoulder"],
             calories_per_min=6.0,
             instructions=[
                 "Grip parallel bars, arms straight, lean torso forward 30–45°",
                 "Lower until upper arms are parallel to floor",
                 "Keep elbows slightly flared, not pinned tight",
                 "Drive back up through your chest, not your triceps",
             ]),
    _compact("Decline Barbell Press",
             "Lower-chest compound press on a decline bench.",
             ["chest", "triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Decline-Barbell-Bench-Press.gif",
             ["barbell", "decline bench"], exercise_type="compound",
             split_tags=["push", "chest_shoulder"], calories_per_min=6.0,
             difficulty="intermediate"),
    _compact("Pec Deck Fly",
             "Machine chest isolation — constant tension through the full arc.",
             ["chest"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pec-Deck-Fly.gif",
             ["pec deck machine"], exercise_type="isolation",
             split_tags=["push", "chest_shoulder"], calories_per_min=4.0),
    _compact("Low-to-High Cable Fly",
             "Cable fly from low pulley — emphasises upper pecs.",
             ["chest", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Low-Cable-Fly.gif",
             ["cable machine"], exercise_type="isolation",
             split_tags=["push", "chest_shoulder"], calories_per_min=4.0),
    _compact("Decline Push-up",
             "Feet elevated push-up — shifts load to upper chest.",
             ["chest", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Decline-Push-Up.gif",
             [], exercise_type="compound",
             split_tags=["push", "chest_shoulder", "bodyweight"], calories_per_min=5.0),
    _compact("Incline Barbell Press",
             "Barbell press on 30° incline — upper chest mass builder.",
             ["chest", "shoulders", "triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Barbell-Bench-Press.gif",
             ["barbell", "incline bench", "rack"], exercise_type="compound",
             split_tags=["push", "chest_shoulder"], calories_per_min=6.5,
             difficulty="intermediate"),

    # ── Back expansion (targeting 13 total) ─────────────────────────────────
    _compact("T-Bar Row",
             "Chest-supported or landmine row — heavy mid-back thickness.",
             ["back", "biceps", "rear delts"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/T-Bar-Row.gif",
             ["T-bar machine", "barbell"], exercise_type="compound",
             split_tags=["pull", "back_bicep"], calories_per_min=7.0,
             difficulty="intermediate"),
    _compact("Chest-Supported Row",
             "Lie on incline bench, row dumbbells — eliminates lower back fatigue.",
             ["back", "rear delts"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Incline-Row.gif",
             ["dumbbells", "incline bench"], exercise_type="compound",
             split_tags=["pull", "back_bicep"], calories_per_min=5.5),
    _compact("Meadows Row",
             "Single-arm landmine row for lat and upper-back width.",
             ["back", "biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2022/07/Meadows-Row.gif",
             ["barbell", "landmine"], exercise_type="compound",
             split_tags=["pull", "back_bicep"], calories_per_min=5.5,
             difficulty="intermediate"),
    _compact("Supinated Lat Pulldown",
             "Underhand-grip pulldown — bicep involvement, great lat stretch.",
             ["back", "biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Underhand-Lat-Pulldown.gif",
             ["lat pulldown machine"], exercise_type="compound",
             split_tags=["pull", "back_bicep"], calories_per_min=5.5),
    _compact("Single-Arm Cable Row",
             "Unilateral cable row — fix side-to-side imbalances.",
             ["back", "biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/One-Arm-Cable-Row.gif",
             ["cable machine"], exercise_type="compound",
             split_tags=["pull", "back_bicep"], calories_per_min=5.0),
    _compact("Inverted Row",
             "Bodyweight horizontal row using a bar or Smith machine.",
             ["back", "biceps", "rear delts"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Inverted-Row.gif",
             [], exercise_type="compound",
             split_tags=["pull", "back_bicep", "bodyweight"], calories_per_min=5.0),

    # ── Shoulders expansion (targeting 10 total) ─────────────────────────────
    _compact("Cable Lateral Raise",
             "Constant-tension lateral raise using a low cable pulley.",
             ["shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Cable-Lateral-Raise.gif",
             ["cable machine"], exercise_type="isolation",
             split_tags=["push", "chest_shoulder"], calories_per_min=3.5),
    _compact("Front Raise",
             "Dumbbell or plate front raise for anterior delt.",
             ["shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Front-Raise.gif",
             ["dumbbells"], exercise_type="isolation",
             split_tags=["push", "chest_shoulder"], calories_per_min=3.5),
    _compact("Machine Shoulder Press",
             "Plate-loaded or selectorised overhead press machine.",
             ["shoulders", "triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Shoulder-Press-Machine.gif",
             ["machine"], exercise_type="compound",
             split_tags=["push", "chest_shoulder"], calories_per_min=5.5),
    _compact("Upright Row",
             "Barbell pull to chin — deltoids + traps. Keep grip wider than shoulder.",
             ["shoulders", "traps", "rear delts"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Upright-Row.gif",
             ["barbell"], exercise_type="compound",
             split_tags=["push", "chest_shoulder"], calories_per_min=5.0,
             difficulty="intermediate"),
    _compact("Band Pull-Apart (Shoulders)",
             "Resistance band pulled apart at shoulder height — rear delt warm-up.",
             ["rear delts", "shoulders"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Band-pull-apart.gif",
             ["resistance band"], exercise_type="isolation",
             split_tags=["pull", "chest_shoulder"], calories_per_min=3.0),

    # ── Biceps expansion ────────────────────────────────────────────────────
    _compact("Spider Curl",
             "Lie chest-down on incline bench, curl upward — peak contraction focus.",
             ["biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Spider-Curl.gif",
             ["dumbbells", "incline bench"], exercise_type="isolation",
             split_tags=["pull", "arm"], calories_per_min=3.5),
    _compact("Preacher Curl",
             "EZ bar or dumbbell curl on a preacher bench — strict form, no swinging.",
             ["biceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Preacher-Curl.gif",
             ["preacher bench", "EZ bar"], exercise_type="isolation",
             split_tags=["pull", "arm"], calories_per_min=3.5),
    _compact("Cross-Body Hammer Curl",
             "Hammer curl crossing body toward opposite shoulder — brachialis peak.",
             ["biceps", "brachialis"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Cross-body-Curl.gif",
             ["dumbbells"], exercise_type="isolation",
             split_tags=["pull", "arm"], calories_per_min=3.5),

    # ── Triceps expansion ────────────────────────────────────────────────────
    _compact("Diamond Push-up",
             "Hands form a diamond shape — intense tricep isolation bodyweight.",
             ["triceps", "chest"],
             "https://fitnessprogramer.com/wp-content/uploads/2022/03/Diamond-Push-Up.gif",
             [], exercise_type="compound",
             split_tags=["push", "arm", "bodyweight"], calories_per_min=5.5),
    _compact("Tricep Kickback",
             "Dumbbell extension to full lockout, hinge at hips — long-head squeeze.",
             ["triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Kickback.gif",
             ["dumbbells"], exercise_type="isolation",
             split_tags=["push", "arm"], calories_per_min=3.0),
    _compact("JM Press",
             "Hybrid tricep movement between skull crusher and close-grip press.",
             ["triceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2022/05/JM-Press.gif",
             ["barbell", "bench"], exercise_type="compound",
             split_tags=["push", "arm"], calories_per_min=5.0, difficulty="advanced"),

    # ── Legs expansion ───────────────────────────────────────────────────────
    _compact("Sumo Squat",
             "Wide-stance squat — greater glute and inner thigh activation.",
             ["legs", "glutes", "quadriceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Sumo-Squat.gif",
             ["barbell", "dumbbells"], exercise_type="compound",
             split_tags=["legs_core"], calories_per_min=7.5),
    _compact("Hack Squat",
             "Machine or barbell hack squat — quad mass with spine support.",
             ["legs", "quadriceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hack-Squat.gif",
             ["hack squat machine"], exercise_type="compound",
             split_tags=["legs_core"], calories_per_min=7.0, difficulty="intermediate"),
    _compact("Glute-Ham Raise",
             "Bodyweight or loaded hamstring curl from the knees.",
             ["legs", "hamstrings", "glutes"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/02/Glute-Ham-Raise.gif",
             ["GHR machine"], exercise_type="compound",
             split_tags=["legs_core"], calories_per_min=6.5, difficulty="advanced"),
    _compact("Step-up",
             "Step onto a box with a dumbbell — unilateral quad + glute builder.",
             ["legs", "glutes", "quadriceps"],
             "https://fitnessprogramer.com/wp-content/uploads/2021/06/Dumbbell-Step-Up.gif",
             ["dumbbells", "box"], exercise_type="compound",
             split_tags=["legs_core"], calories_per_min=6.5),
])


# ─── Merge science-backed enrichment into seed data ──────────────────────────
for _ex in SEED_EXERCISES:
    _enrich = ENRICHMENT.get(_ex["name"])
    if _enrich:
        for _key, _val in _enrich.items():
            if _key not in _ex:  # don't override existing enrichment (e.g. chest exercises already enriched inline)
                _ex[_key] = _val


def seed_exercise_library(db: Session) -> int:
    """Seed the exercise library with common exercises. Always upserts enrichment fields."""
    seeded = 0
    enrichment_fields = [
        "emg_rank", "muscle_primary", "muscle_secondary",
        "reps_min", "reps_max", "rest_seconds",
        "tempo_eccentric", "tempo_concentric",
        "starting_weight_mult_male", "starting_weight_mult_female",
        "posture_correction_tags", "progressions", "regressions",
    ]

    for ex in SEED_EXERCISES:
        existing = db.query(ExerciseLibrary).filter(
            ExerciseLibrary.name == ex["name"]
        ).first()
        if existing:
            # Always upsert enrichment + base fields
            existing.calories_per_min = ex.get("calories_per_min", existing.calories_per_min)
            existing.exercise_type = ex.get("exercise_type", existing.exercise_type)
            existing.split_tags = ex.get("split_tags", existing.split_tags)
            existing.instructions_json = ex.get("instructions_json", existing.instructions_json)
            existing.common_mistakes = ex.get("common_mistakes", existing.common_mistakes)
            existing.muscle_groups = ex.get("muscle_groups", existing.muscle_groups)
            # Only overwrite image_url if the seed has a non-empty value AND the
            # current DB value is empty/seeded-default. This preserves any URL the
            # operator has manually fixed via the admin patch endpoint.
            new_url = ex.get("image_url", "") or ""
            if new_url and (not existing.image_url or existing.image_url.startswith("https://fitnessprogramer.com/")):
                # Probe lightly: only swap if new is truthy; let manual fixes win
                # (manual fixes will not start with fitnessprogramer.com prefix)
                if not existing.image_url:
                    existing.image_url = new_url
            existing.difficulty = ex.get("difficulty", existing.difficulty)
            existing.equipment_needed = ex.get("equipment_needed", existing.equipment_needed)
            for field in enrichment_fields:
                if field in ex:
                    setattr(existing, field, ex[field])
            continue

        db.add(ExerciseLibrary(
            name=ex["name"],
            description=ex["description"],
            instructions_json=ex["instructions_json"],
            muscle_groups=ex["muscle_groups"],
            common_mistakes=ex["common_mistakes"],
            image_url=ex["image_url"],
            difficulty=ex["difficulty"],
            equipment_needed=ex["equipment_needed"],
            calories_per_min=ex.get("calories_per_min", 5.0),
            exercise_type=ex.get("exercise_type", "compound"),
            split_tags=ex.get("split_tags", []),
            **{f: ex[f] for f in enrichment_fields if f in ex},
        ))
        seeded += 1

    db.commit()
    return seeded


# MET values reference for calorie estimation
# Source: Compendium of Physical Activities (Ainsworth et al.)
MET_VALUES = {
    "compound_heavy": 8.0,     # Squat, Deadlift, Bench Press
    "compound_medium": 6.0,    # Rows, OHP, Lunges
    "isolation": 3.5,          # Curls, extensions, raises
    "isometric": 3.5,          # Plank, wall sit
    "cardio_high": 12.0,       # Burpees, jump rope intense
    "cardio_medium": 8.0,      # Running, cycling moderate
    "stretch": 2.0,            # Mobility, yoga
}


def estimate_calories_burned(
    exercise_name: str,
    duration_minutes: float,
    user_weight_kg: float,
    exercise_type: str = "compound",
    calories_per_min_override: float = None,
) -> float:
    """
    Estimate calories burned using MET values.
    Formula: Calories = MET × weight_kg × duration_hours
    Returns kcal burned.
    """
    if calories_per_min_override and calories_per_min_override > 0:
        # Scale from reference 75kg to actual user weight
        scale = user_weight_kg / 75.0
        return round(calories_per_min_override * scale * duration_minutes, 1)

    met_map = {
        "compound": MET_VALUES["compound_medium"],
        "isolation": MET_VALUES["isolation"],
        "isometric": MET_VALUES["isometric"],
        "cardio": MET_VALUES["cardio_medium"],
        "stretch": MET_VALUES["stretch"],
    }
    met = met_map.get(exercise_type, 5.0)
    duration_hours = duration_minutes / 60.0
    return round(met * user_weight_kg * duration_hours, 1)
