"""Add missing fields to exercise library

Revision ID: 0ae35cf138d4
Revises: ccdfed0298e9
Create Date: 2026-04-16 13:28:38.233472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae35cf138d4'
down_revision: Union[str, Sequence[str], None] = 'ccdfed0298e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('supplement_logs'):
        op.create_table('supplement_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('supplement_name', sa.String(length=50), nullable=False),
        sa.Column('dose_g', sa.Float(), nullable=True),
        sa.Column('taken_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('supplement_logs', schema=None) as batch_op:
            batch_op.create_index('ix_supplement_logs_user_date', ['user_id', 'date'], unique=False)
            batch_op.create_index(batch_op.f('ix_supplement_logs_user_id'), ['user_id'], unique=False)

    if not inspector.has_table('user_reminders'):
        op.create_table('user_reminders',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reminder_type', sa.String(length=30), nullable=False),
        sa.Column('time_hhmm', sa.String(length=5), nullable=False),
        sa.Column('timezone_offset', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('days_of_week', sa.JSON(), nullable=True),
        sa.Column('last_sent_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('user_reminders', schema=None) as batch_op:
            batch_op.create_index('ix_user_reminders_user', ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_reminders_user_id'), ['user_id'], unique=False)

    if not inspector.has_table('exercise_sessions'):
        op.create_table('exercise_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('exercise_name', sa.String(length=100), nullable=False),
        sa.Column('sets_log_json', sa.JSON(), nullable=True),
        sa.Column('rest_seconds_total', sa.Integer(), nullable=True),
        sa.Column('total_duration_s', sa.Integer(), nullable=True),
        sa.Column('calories_burned', sa.Float(), nullable=True),
        sa.Column('user_weight_kg', sa.Float(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
            batch_op.create_index('ix_exercise_sessions_user_date', ['user_id', 'date'], unique=False)
            batch_op.create_index(batch_op.f('ix_exercise_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resting_hr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('floors_climbed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wearable_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('exercise_calories', sa.Integer(), nullable=True))

    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exercise_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('split_tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.drop_column('split_tags')
        batch_op.drop_column('exercise_type')
        batch_op.drop_column('calories_per_min')

    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.drop_column('exercise_calories')
        batch_op.drop_column('wearable_source')
        batch_op.drop_column('floors_climbed')
        batch_op.drop_column('resting_hr')
        batch_op.drop_column('active_calories')

    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_sessions_user_id'))
        batch_op.drop_index('ix_exercise_sessions_user_date')

    op.drop_table('exercise_sessions')
    with op.batch_alter_table('user_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reminders_user_id'))
        batch_op.drop_index('ix_user_reminders_user')

    op.drop_table('user_reminders')
    with op.batch_alter_table('supplement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplement_logs_user_id'))
        batch_op.drop_index('ix_supplement_logs_user_date')

    op.drop_table('supplement_logs')
    # ### end Alembic commands ###
