"""reconcile_schema_drift

Revision ID: 1abf6b17232e
Revises: a3b4c5d6e7f8
Create Date: 2026-06-20 01:23:29.674675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abf6b17232e'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_messages', schema=None) as batch_op:
        batch_op.alter_column('flagged_injury',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cycle_logs', schema=None) as batch_op:
        batch_op.alter_column('cycle_length',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'28'"))
        batch_op.create_index(batch_op.f('ix_cycle_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user'))
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_scores_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_sync_token', ['sync_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_sync_token', type_='unique')

    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_scores_user_id'))

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.create_index(batch_op.f('ix_feedback_user'), ['user_id'], unique=False)

    with op.batch_alter_table('cycle_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_logs_user_id'))
        batch_op.alter_column('cycle_length',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'28'"))

    with op.batch_alter_table('coach_messages', schema=None) as batch_op:
        batch_op.alter_column('flagged_injury',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
