"""initial schema with all models

Revision ID: 2c4345c72e77
Revises: 
Create Date: 2026-04-06 14:33:24.578360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4345c72e77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('ovr_bonus', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_key')
    )
    op.create_table('exercise_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions_json', sa.JSON(), nullable=True),
    sa.Column('muscle_groups', sa.JSON(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('equipment_needed', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nutrients_per_100g_json', sa.JSON(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.create_index('ix_food_cache_source', ['source', 'source_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('ovr_rating', sa.Float(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('streak_freezes', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('registration_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_truth_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('registration_data_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('comp_type', sa.String(length=20), nullable=True),
    sa.Column('challenge_type', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_invite_code'), ['invite_code'], unique=True)

    op.create_table('habit_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_name', sa.String(length=50), nullable=False),
    sa.Column('quit_date', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_trackers_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_grams', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fibre_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=30), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.create_index('ix_nutrition_logs_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_logs_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=True),
    sa.Column('daily_protein_g', sa.Float(), nullable=True),
    sa.Column('daily_carbs_g', sa.Float(), nullable=True),
    sa.Column('daily_fat_g', sa.Float(), nullable=True),
    sa.Column('daily_fibre_g', sa.Float(), nullable=True),
    sa.Column('meal_timing_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_targets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_nutrition_targets_user_week', ['user_id', 'week_start'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index('ix_user_badges_user_badge', ['user_id', 'badge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('user_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('bicep_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_user_metrics_user_date', ['user_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('user_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('ai_analysis_json', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_photos_user_id'), ['user_id'], unique=False)

    op.create_table('user_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_plans_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_plans_user_week', ['user_id', 'week_start'], unique=False)

    op.create_table('weekly_plan_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('input_context_json', sa.JSON(), nullable=True),
    sa.Column('output_plan_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_plan_cycles', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_cycles_user_week', ['user_id', 'week_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_plan_cycles_user_id'), ['user_id'], unique=False)

    op.create_table('competition_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_total', sa.Integer(), nullable=True),
    sa.Column('streak_bonus', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.create_index('ix_comp_members_comp_user', ['competition_id', 'user_id'], unique=True)

    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('task_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('exercise_sets', sa.String(length=30), nullable=True),
    sa.Column('exercise_weight', sa.String(length=30), nullable=True),
    sa.Column('actual_weight_used', sa.String(length=30), nullable=True),
    sa.Column('exercise_library_id', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_library_id'], ['exercise_library.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_daily_tasks_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index('ix_daily_tasks_user_date_section', ['user_id', 'date', 'section'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('recommended_weight', sa.String(length=30), nullable=True),
    sa.Column('actual_weight', sa.String(length=30), nullable=True),
    sa.Column('sets_completed', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_weight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_weight_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_weight_logs_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_weight_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_weight_logs_user_date')
        batch_op.drop_index(batch_op.f('ix_exercise_weight_logs_user_id'))

    op.drop_table('exercise_weight_logs')
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_tasks_user_id'))
        batch_op.drop_index('ix_daily_tasks_user_date_section')
        batch_op.drop_index('ix_daily_tasks_user_date')

    op.drop_table('daily_tasks')
    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.drop_index('ix_comp_members_comp_user')

    op.drop_table('competition_members')
    with op.batch_alter_table('weekly_plan_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_plan_cycles_user_id'))
        batch_op.drop_index('ix_weekly_cycles_user_week')

    op.drop_table('weekly_plan_cycles')
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_user_plans_user_week')
        batch_op.drop_index(batch_op.f('ix_user_plans_user_id'))

    op.drop_table('user_plans')
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_photos_user_id'))

    op.drop_table('user_photos')
    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_metrics_user_id'))
        batch_op.drop_index('ix_user_metrics_user_date')

    op.drop_table('user_metrics')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index('ix_user_badges_user_badge')

    op.drop_table('user_badges')
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.drop_index('ix_nutrition_targets_user_week')
        batch_op.drop_index(batch_op.f('ix_nutrition_targets_user_id'))

    op.drop_table('nutrition_targets')
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_logs_user_id'))
        batch_op.drop_index('ix_nutrition_logs_user_date')

    op.drop_table('nutrition_logs')
    with op.batch_alter_table('habit_trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_trackers_user_id'))

    op.drop_table('habit_trackers')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_invite_code'))

    op.drop_table('competitions')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))

    op.drop_table('achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('food_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_food_cache_source')

    op.drop_table('food_cache')
    op.drop_table('exercise_library')
    op.drop_table('badges')
    # ### end Alembic commands ###
