"""Add exercise intelligence fields

Revision ID: 61f8d94d37aa
Revises: 0ae35cf138d4
Create Date: 2026-04-24 06:32:48.353891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f8d94d37aa'
down_revision: Union[str, Sequence[str], None] = '0ae35cf138d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emg_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('muscle_primary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('muscle_secondary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reps_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_eccentric', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_concentric', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('starting_weight_mult_male', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('starting_weight_mult_female', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('posture_correction_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('progressions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('regressions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.drop_column('regressions')
        batch_op.drop_column('progressions')
        batch_op.drop_column('posture_correction_tags')
        batch_op.drop_column('starting_weight_mult_female')
        batch_op.drop_column('starting_weight_mult_male')
        batch_op.drop_column('tempo_concentric')
        batch_op.drop_column('tempo_eccentric')
        batch_op.drop_column('rest_seconds')
        batch_op.drop_column('reps_max')
        batch_op.drop_column('reps_min')
        batch_op.drop_column('muscle_secondary')
        batch_op.drop_column('muscle_primary')
        batch_op.drop_column('emg_rank')

    # ### end Alembic commands ###
