"""add daily_health_logs table

Revision ID: ccdfed0298e9
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 13:32:21.901802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdfed0298e9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('supplements_taken', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_health_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_daily_health_user_date', ['user_id', 'date'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_health_user_date')
        batch_op.drop_index(batch_op.f('ix_daily_health_logs_user_id'))

    op.drop_table('daily_health_logs')
    # ### end Alembic commands ###
